### DISCUSSION TITLE
如何隐藏某些辅助方案？

### DISCUSSION THREAD

**Discussion by forfudan** [imfuxiao/Hamster#163] [Q&A]
假设某个方案 A.schema.yaml 需要调用若干辅助方案，如 B.schema.yaml。那么，应该修改哪个文件，使得在方案列表中隐藏这些辅助方案？

**Comment by imfuxiao** [comment]
在最终的 `default.yaml` 里面，

```yaml
schema_list:
  - schema: clover
  - schema: double_pinyin
  - schema: double_pinyin_flypy
  - schema: wubi86
  - schema: xkjd6
  - schema: xmjd6
  - schema: xmjd6en
  - schema: yuhao
  - schema: yuhao_pinyin
  - schema: yuhao_tradition
```
排除不想要的方案
