### DISCUSSION TITLE
皮肤怎么弄啊

### DISCUSSION THREAD

**Discussion by dnxxymcj** [imfuxiao/Hamster#169] [Q&A]
直接用鼠须管里的皮肤，效果不太对，弄个示例吧，我照着改改，谢谢大佬了。

**Comment by imfuxiao** [comment]
配色方案在 SharedSupport 下的 squirrel.yaml 文件中。可以看到 color_schemes 相关字样。键值对应可以参考 https://gjrobert.github.io/Rime-See-Me-squirrel/ 这个连接

**Reply by imfuxiao** [reply]
修改完了，自己最好备份下，完了通过浏览器上传上去，在点击重新部署。

**Comment by Jreen** [comment]
不知道为什么在tf版本里面，我弄的皮肤没有生效？
```
patch:
  app_options:
    {}
  style:
    color_scheme: wechat_light
    horizontal: true
    inline_preedit: true
  
  preset_color_schemes:
    wechat_light:
      name: "微信浅色／Wechat Light"
      author: 小码哥
      color_space: srgb                       # 色彩空间： srgb | display_p3
      back_color: 0xFFFFFF                    # 底色
      hilited_candidate_back_color: 0x79af22  # 选中底色
      label_color: 0x999999                   # 序号颜色
      hilited_candidate_label_color: 0xFFFFFF # 选中序号颜色
      candidate_text_color: 0x3c3c3c          # 文字颜色
      hilited_candidate_text_color: 0xFFFFFF  # 选中文字颜色
      comment_text_color: 0x999999            # 注颜色
      hilited_comment_text_color: 0x999999    # 选中注颜色
      text_color: 0x424242                    # 拼音颜色 （inline_preedit: false）
      hilited_text_color: 0x999999            # 选中拼音颜色 （inline_preedit: false）
      candidate_back_color: 0xFFFFFF          # 候选项底色
      #preedit_back_color:                   # 拼音底色 （inline_preedit: false）
      hilited_back_color: 0x79af22            # 选中拼音底色 （inline_preedit: false）
      border_color: 0xFFFFFF                  # 外边框颜色
```
