### ISSUE TITLE
功能请求：支持 switches (开关)

### ISSUE THREAD

**Issue by amorphobia** [imfuxiao/Hamster#133]
各个方案会有一些自定义的 `switches`，例如键道定义了：

```yaml
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: jffh
    reset: 0
    states: [ 简体, 繁體 ]
  - name: sbb_hint
    reset: 1 # 改成0默认关闭
    states: [ "关₆₃₀", "开₆₃₀" ]
  - name: sbb_disable_full
    reset: 0 # 改成1默认关闭全码
    states: [ "开₆₃₀全码", "关₆₃₀全码" ]
  - name: EN2en
    reset: 1
  - name: topup_hint
    reset: 1
    states: [ "关顶功提示", "开顶功提示" ]
```

在电脑上，可以通过 `F4` 或 ``Ctrl + ` `` 来呼出开关：
![图片](https://user-images.githubusercontent.com/523025/233816573-42b09bcd-1165-40e7-b8cf-1fed969d526f.png)

安卓平台也支持 `switches`，开关会显示在候选栏里：
![图片](https://user-images.githubusercontent.com/523025/233816599-942acfb0-420e-4bab-9bfb-459dca6718c1.png)

值得注意的是，`switches` 可以定义多于两种 states，如：
```yaml
switches:
  - options: [utf8, gbk, gb2312]    # (※2) 字符集选单 
    reset: 1                        # 默认 GBK
    states:                         # 可以通过切功能键，切至 UTF8 等超大字符集
      - UTF-8
      - GBK
      - GB2312
```
