### ISSUE TITLE
补充Hamster文档

### ISSUE THREAD

**Issue by imfuxiao** [imfuxiao/Hamster#14]
补充Hamster使用说明文档
#12

**Comment by Attiv** [comment]
@imfuxiao  键盘背景色和按钮背景色的值可以先说明下么，想加个主题

**Comment by imfuxiao** [comment]
> @imfuxiao 键盘背景色和按钮背景色的值可以先说明下么，想加个主题

参考这个 https://gjrobert.github.io/Rime-See-Me-squirrel/, 代码读取yaml中的key和这个是相同的

(连接来源: https://github.com/rime/squirrel/wiki)

**Comment by lewangdev** [comment]
文档是否可以开启项目的 wiki 来进行编写，我可以参与来编写仓输入法/rime 使用的文档

**Comment by imfuxiao** [comment]
太好了,非常感谢您的参与,正愁没空写文档.

**Comment by Attiv** [comment]
> > @imfuxiao 键盘背景色和按钮背景色的值可以先说明下么，想加个主题
> 
> 参考这个 https://gjrobert.github.io/Rime-See-Me-squirrel/, 代码读取 yaml 中的 key 和这个是相同的
> 
> (连接来源: https://github.com/rime/squirrel/wiki)

有个问题，键盘上按键比如 qwer 的背景色是哪个？我想做个类似原生的那样的，但是没试出来键盘每个按键的颜色是什么。比如这个配色：
```
    wechat:
      name: '微信键盘 / WeChat-keyboard' # 配色取自微信键盘
      author: zsakvo
      back_color: 0xE2E3E6
      border_height: 3
      # border_color: 0xE0B693
      border_width: 8
      candidate_format: '%c %@ '
      comment_text_color: 0x999999
      corner_radius: 5
      hilited_corner_radius: 5
      font_face: PingFangSC
      font_point: 16
      hilited_candidate_back_color: 0x75B100
      hilited_candidate_text_color: 0xFFFFFF
      horizontal: true
      inline_preedit: true
      label_font_point: 12
      text_color: 0x424242
```
