### ISSUE TITLE
关于调用自定义键盘使用 keyboardType(custom(name)) 参数无法正常使用

### ISSUE THREAD

**Issue by Azeril** [imfuxiao/Hamster#308]
这两天在摸索 TF 新发布的 3.0 版. 自己自定义了一下 Dvorak 键盘布局. 但发现 没法在使用中文的 Dvorak 键盘锁定大写时 保持在原键盘（会自动跳到英文键盘的大写模式下去 而那个键盘所基于的布局是无法调整的 也就是传统英文键盘的布局）. 

鉴于这个问题 加上我也不清楚未来作者是否会支持自定义原始键盘的参数. 就想着 目前凑合使用的话 或许可以通过另外自己弄一个 Dvorak 布局的英文大写键盘 然后自己在中文 Dvorak 键盘的一个按键中使用
 - action: keyboardType(custom(name))
 - 
进行绑定. 实现跳转 也能变相实现当前所需的功能. 

在 custom.yaml 文档中 涉及跳转按钮的参数 具体是这样的样式：

```
    - keys:   ## 第三行 行首
      - action: keyboardType(custom(仓颉)) ## Dvorak 大写键盘 跳转
        width:
          portrait: input ## percentage(0.13)
          landscape: input ## percentage(0.13)
        label:
          loadingText: ''
          text: ''
        processByRIME: true
        swipe: []
``` 

但实际的测试发现 该参数无法正常使用 绑定键在部署后都是点击后无法跳转的状态. 一开始我以为是不支持 name 大写命名啥的 把键盘命名都改成了中文 还是不行. 再修改成键盘自定义文档里默认有的仓颉的参数 也还是不行 才意识到这可能是 bug...

希望作者有空能看一下 并修复一下这个问题.
