### ISSUE TITLE
2.0内测作为第一次使用的建议：

### ISSUE THREAD

**Issue by Jreen** [imfuxiao/Hamster#316]
1、“重新部署”建议在比较醒目的位置如题，我一个一个点才找到：“重新部署”。
2、比如我打“你好”的拼音比较小
3、9宫那个字母比较紧密 能稍微松点吗？
4、比如abc就划为一个框，能带口那种的感觉吗？就像iPhone自带键盘那种的框

**Comment by Jreen** [comment]
还有一个问题
就是一列app那块，还有siri建议那块 键盘就出现空白了。

![IMG_9484](https://github.com/imfuxiao/Hamster/assets/3260505/0c916704-101a-4876-af58-7b2b3dc42b6f)

**Comment by Jreen** [comment]
然后还有一个问题，就是配色方案建议增加微信皮肤那个

```
    wechat_light:
      name: "微信浅色／Wechat Light"
      author: 小码哥
      horizontal: false
      font_face: "LXGW WenKai"          # 字体及大小
      font_point: 18
      label_font_face: "PingFangSC"    # 序号字体及大小
      label_font_point: 13
      comment_font_face: "PingFangSC"  # 注字体及大小
      comment_font_point: 16
      candidate_format: "%c\u2005%@\u2005" # 编号 %c 和候选词 %@ 前后的空间
      candidate_list_layout: stacked   # 候选排布：层叠 stacked | 行 linear
      text_orientation: horizontal    # 行文向： 横 horizontal | 纵 vertical
      inline_preedit: true            # 拼音位于： 候选框 false | 行内 true
      translucency: true             # 磨砂： false | true
      mutual_exclusive: false         # 色不叠加： false | true
      border_height: 1                # 外边框 高
      border_width: 1                 # 外边框 宽
      corner_radius: 5                # 外边框 圆角半径
      hilited_corner_radius: 5       # 选中框 圆角半径
      surrounding_extra_expansion: 0 # 候选项背景相对大小
      shadow_size: 0                 # 阴影大小
      line_spacing: 5                # 行间距
      base_offset: 0                 # 字基高
      alpha: 1                       # 透明度，0~1
      spacing: 10                    # 拼音与候选项之间的距离 （inline_preedit: false）
      color_space: srgb                       # 色彩空间： srgb | display_p3
      back_color: 0xFFFFFF                    # 底色
      hilited_candidate_back_color: 0x79af22  # 选中底色
      label_color: 0x999999                   # 序号颜色
      hilited_candidate_label_color: 0xFFFFFF # 选中序号颜色
      candidate_text_color: 0x3c3c3c          # 文字颜色
      hilited_candidate_text_color: 0xFFFFFF  # 选中文字颜色
      comment_text_color: 0x999999            # 注颜色
      hilited_comment_text_color: 0x999999    # 选中注颜色
      text_color: 0x424242                    # 拼音颜色 （inline_preedit: false）
      hilited_text_color: 0x999999            # 选中拼音颜色 （inline_preedit: false）
      candidate_back_color: 0xFFFFFF          # 候选项底色
      # preedit_back_color:                   # 拼音底色 （inline_preedit: false）
      hilited_back_color: 0x79af22            # 选中拼音底色 （inline_preedit: false）
      border_color: 0xFFFFFF                  # 外边框颜色
```
