### ISSUE TITLE
在 `label` 中顯示輸入法狀態

### ISSUE THREAD

**Issue by amorphobia** [imfuxiao/Hamster#367]
用户可以在 `label` (`text`, `loadingText`) 設置格式化字符串，使用形如 `{ascii_mode}`, `{full_shape}`, `{ascii_punct}`, `{schema_name}` 的占位符表示具體狀態。

理論上所有按鍵都可以設置 `label`，衹不過短的按鍵可能衹能顯示一個字符。

比如我設置了空格的 label 爲 `"{ascii_mode} - {schema_name}"`，那麽（在不超出邊緣的情况下），空格上的顯示就爲 `中 - 鍵道` 或 `En - 鍵道` 這樣的文字。

某一狀態具體顯示的字符串可以由用户自定義，例如

```yaml
switcheStatus: # 或者叫其他更好的鍵名
  ascii_mode:
    - "中" # ascii_mode 是 0 時顯示，字符串可以是空的，等效于在這個狀態下不顯示
    - "En" # ascii_mode 是 1 時顯示
  full_shape:
    - "全"
    - "半"
  ascii_punct:
    - "，。"
    - ",."
  emoji: # 可以是方案特有的 swich 
    - "無"
    - "🈶️"
```
