### ISSUE TITLE
关于自定义键盘布局一对多按键的映射问题

### ISSUE THREAD

**Issue by ccomac** [imfuxiao/Hamster#385]
作者您好，因为最近的 TF 版已经支持了九宫格布局和自定义布局，所以我也想模仿着做一个双键的布局，但在按键映射的时候遇到了一点问题。

首先我参考了一下 https://lost-melody.github.io/hamster-tools 里预置的 14 双键模板，它是这么定义的，比如【QW】键

```yaml
          - action: character(q)
            width: percentage(0.2)
            label: QW
```

这样相当于只传入了按键的首字母 q，虽然不影响双键布局的实现，但这时候选栏顶部的拼音却是不正确的。具体情况如下：

首先以内置的九宫格为例，当我按下 3264 的时候，第一个候选字是「放」，拼音也是 fang，虽然实际上这几个按键的首字母是 damg：

![image](https://github.com/imfuxiao/Hamster/assets/89504429/bd9e2a0e-5a00-4f80-9617-55ff888fe6d8)

但在我自定义的布局中（我实现双键的方法也是参考雾凇九宫格的「穷举后拼音的模糊匹配」），候选栏顶部的拼音却并不是第一个候选字（词组）的拼音，而是按键的首字母。如图，正确的拼音（我使用了双拼，并关闭了双拼还原）应该是：ce ii yi xx xb go，虽然输入法正确命中了这个词组，但是拼音却显示错误。

![image](https://github.com/imfuxiao/Hamster/assets/89504429/8efb3822-d3e8-4fbc-bc61-30e05109baff)

所以我有一点疑问，内置的九宫格布局的按键对应的 `action` 是什么样的，我看了一下默认的 hamster.yaml 文件，里面关于滑动设置的部分出现了一个《[自定义键盘布局](https://github.com/imfuxiao/Hamster/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E9%94%AE%E7%9B%98%E5%B8%83%E5%B1%80#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%94%AE%E7%9B%98%E5%B8%83%E5%B1%80)》文档里没有的写法 `chineseNineGrid(string)`：

```yaml
        - action: chineseNineGrid(ABC)
          swipe:
            - direction: up
              action: character(2)
              display: true
```

于是我尝试了一下将【QW】按键的 `action` 改成 `chineseNineGrid(QW)`，但结果还是只能显示错误的按键首字母拼音，所以想请教一下，该如何映射才能让自定义键盘布局实现和内置九宫格一样的效果呢？感谢。
