### ISSUE TITLE
上滑或下滑过于灵敏，容易误触

### ISSUE THREAD

**Issue by Pansamore** [imfuxiao/Hamster#419]
使用了三天，最突出的就是滑动的误触问题，感觉过于灵敏了。只是打字，但是常常会打出符号。希望可以提升。

**Comment by imfuxiao** [comment]
您好，划动的手势识别有两个参数，一个是划动的角度(tangentThreshold)，一个是划动的距离(distanceThreshold)。

角度是指，已你按键触发的点为起点，释放点为终点。两点间的水平方向夹角或垂直方向夹角。
距离是指，按键触发点为起点，释放点为终点，两点键的距离。

```yaml
swipe:
  # 划动距离阈值，当划动的距离大于或等于此值时，才会识别为一次划动
  distanceThreshold: 20
  # 此值是正切角度的阈值，用来限制上下左右划动时的角度，如果太大容易误触
  # 默认为 15 度的正切值，即上下左右划的的角度不能超过 15 度
  # tan(10º) ≈ 0.176, tan(15º) ≈ 0.268, tan(30º) ≈ 0.577, tan(45º) = 1, tan(60º) ≈ 1.732
  tangentThreshold: 0.666
```

您可以适当调整这两个参数的值。

如何调节，举例：

1. 新建 hamster.custom.yaml 文件。
2. 文件内容如下：
```yaml
patch:
  swipe:
    distanceThreshold: 20
    tangentThreshold: 0.666
```
3. 将文件通过 仓 内置的 `WiFi 上传文件`，将文件存放至 `Rime` 目录下。
4. 重新部署
