### ISSUE TITLE
希望可以关闭emoji项

### ISSUE THREAD

**Issue by kefengzhang** [imfuxiao/Hamster#427]
我现在使用clover输入法,日常使用emoji并不多,增加emoji后会使我候选词过多,所以我想关闭emoji项

在修改 方案管理->应用文件->SharedSupport->clover.schema.yaml内的如下内容:
 - name: emoji_suggestion
    reset: 1
    states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
我将rest:1改为0
重新部署,后会改回1

请问我在什么地方可以关闭 clover输入法的emoji项

**Comment by kefengzhang** [comment]
忘记说了,我是在iphone里面

**Comment by xubai2001** [comment]
试试在应用文件/Rime 下新建文件clover.custom.yaml，然后填入修改后的，下面是我自己的配置中的，你要替换为clover.schema.yaml内这部分内容(修改后的)
```yaml
patch:
	switches:
    - name: ascii_mode
      states: [ 中, Ａ ]
      reset: 0
    - name: ascii_punct # 中英标点
      states: [ ¥, $ ]
      reset: 0
    - name: traditionalization
      states: [ 简, 繁 ]
      reset: 0
    - name: emoji
      states: [ 💀, 😄 ]
      reset: 1
```
