### ISSUE TITLE
升级新版本 2.2.0 后部署异常

### ISSUE THREAD

**Issue by shuxiao9058** [imfuxiao/Hamster#471]
错误日志如下：

![IMG_0546](https://github.com/imfuxiao/Hamster/assets/3312525/9ce953f8-3a9d-4bbd-bee5-93a6fa915bfe)

详情见附件。

[20231223-102854.log](https://github.com/imfuxiao/Hamster/files/13757743/20231223-102854.log)

但是配置文件均是 double 类型。

``` yaml
swipe:
  xAxleSwipeSensitivity: 20
  yAxleSwipeSensitivity: 30
  spaceSwipeSensitivity: 50
  distanceThreshold: 20
  tangentThreshold: 2.68e-1
  longPressDelay: 3e-1
```

所以，不知道问题出在哪里？
