### ISSUE TITLE
character action 无法发送大写字母

### ISSUE THREAD

**Issue by ksqsf** [imfuxiao/Hamster#485]
目前使用如下设置：

```
          - action: { character: { char: W } }
            width: input
            label: we
            swipe:
              - action: { character: { char: "e" } }
                display: true
                processByRIME: true
                direction: right
              - action: { character: { char: "w" } }
                display: true
                processByRIME: true
                direction: left
```

即把 w和e 合并到一键上，在单独按下时发送大写的 `W` 给 rime，但是使用最新商店版（2.2.0）实际测试发现，按下该键时发送的是小写的 `w` 而不是大写的 `W`。但根据文档，应该可以支持发送大写字母。

> character: { char: 字符 }：表示物理键盘的字符按键，其中字符表示具体的 ASCII 字符。
>
> 例如：a 键的配置为 action: { character: { char: a } }，注意是小写，如果想显示为大写可以通过 label 属性配置实现。
