### ISSUE TITLE
长显文本和加载文本显示在数字九宫格的空格上

### ISSUE THREAD

**Issue by yett1873** [imfuxiao/Hamster#489]
如图，自定义键盘的其它配置都正常，但长显和加载文本不知为何跑到了九宫格键盘的空格上↓
![IMG_0936](https://github.com/imfuxiao/Hamster/assets/75569851/f028f87c-1bbf-484a-b27b-2be59dc51cfb)
![IMG_0935](https://github.com/imfuxiao/Hamster/assets/75569851/f2a3c40e-77f7-423c-aa6a-8debf7d90c3c)
```yaml
    # 是否启用空格加载文本
    enableLoadingTextForSpaceButton: true
    # 空格按钮加载文本
    loadingTextForSpaceButton: "加载文本"
    # 空格按钮长显文本
    labelTextForSpaceButton: "️长显文本"
    # 空格按钮长显为当前输入方案
    # 当开启此选项后，labelForSpaceButton 设置的值无效
    showCurrentInputSchemaNameForSpaceButton: false
    # 空格按钮加载文字显示当前输入方案
    # 当开启此选项后， loadingTextForSpaceButton 设置的值无效
    showCurrentInputSchemaNameOnLoadingTextForSpaceButton: false
```
