### ISSUE TITLE
请问切换简繁时，一切到别的app再回去打字需要再次切换简繁有办法解决吗？

### ISSUE THREAD

**Issue by LO-H-W** [imfuxiao/Hamster#504]
我用的是小鹤音形方案，是个码盲，一开始不知道怎么启动切换就弄到翻过去了，5 个小时后才瞎猜到去app上找到切换设定更改名称，
现在遇到一个问题是，我只要切换简繁之后，关掉银幕或跳去别的程式回来打字就老是要再切换一次简繁，
不知道这个困扰是有办法解决的吗？有办法持续让简或繁维持直到再次按下切换吗？
有办法更改预设简体或繁体吗？
具体的步骤麻烦请回答的好心人多多费心，感激不尽，谢谢。

**Comment by imfuxiao** [comment]
目前 option 状态保存，需要通过 Switcher 切换才可以做到。已「雾凇输入方案」为例：

1， 屏蔽输入方案中的 `reset` 选项，比如「雾凇的小鹤双拼」配置文件 `double_pinyin_abc.schema.yaml`。

<img width="533" alt="image" src="https://github.com/imfuxiao/Hamster/assets/6482586/f5fe226a-d5d3-4447-adaf-720d289696e5">

2，为某个键设定划动指令 `#RimeSwitcher`，设定好后，触发后选择「简繁」。

下次启动就是设定的简繁状态了。


https://github.com/imfuxiao/Hamster/assets/6482586/2cd0d6b0-e9fd-4034-8551-1f20191f7a89

**Comment by LO-H-W** [comment]
谢谢你的回复，不过似乎是没有解决到我困扰的问题，我的问题不是无法转换，是转换后不会待下次触发切换指令就自动跳回触发前的状态，每次输入前都要再次切换，我想问的是有没有办法解决让切换持续发生到下次按下切换，或者更改预设简繁设定，谢谢。

**Comment by imfuxiao** [comment]
你的问题难道不是「持久保持简繁状态」，直到自己手动切换么？

**Comment by LO-H-W** [comment]
是的，不过我按照您的步骤问题还是尚未获得改善，不知道是不是我哪裡操作有误呢？

https://github.com/imfuxiao/Hamster/assets/154674265/6998e7f1-cc62-4ce4-a93b-5dd26cb19118

**Comment by imfuxiao** [comment]
还需要调整 default.yaml 或者 default.custom.yaml 中的配置，具体[参考文档](https://ihsiao.com/apps/hamster/docs/Questions.html#%E5%A6%82%E4%BD%95%E6%B0%B8%E4%B9%85%E4%BF%9D%E6%8C%81%E7%AE%80%E7%B9%81%E7%8A%B6%E6%80%81%EF%BC%8C%E7%9B%B4%E5%88%B0%E6%89%8B%E5%8A%A8%E5%88%87%E6%8D%A2%E7%AE%80%E7%B9%81%E7%8A%B6%E6%80%81)。

**Comment by LO-H-W** [comment]
可不可以请你过目一下我这样是出了什么差错，三个颜色都显示不了，最后也没办法使用。
![IMG_6729](https://github.com/imfuxiao/Hamster/assets/154674265/05bf36bf-6404-490f-aa13-6e11ce7ace21)
![IMG_6730](https://github.com/imfuxiao/Hamster/assets/154674265/bc779a47-7194-4c88-8f78-78793723efc6)
![IMG_6728](https://github.com/imfuxiao/Hamster/assets/154674265/acfdcc9b-f349-4340-9e62-9bf88c0e0323)
![IMG_6733](https://github.com/imfuxiao/Hamster/assets/154674265/7b9c1b16-2b51-4194-a78e-5ce8eca10824)
![IMG_6732](https://github.com/imfuxiao/Hamster/assets/154674265/e3e001d7-3505-4cc1-b9f0-8c3c278dc46a)
![IMG_6731](https://github.com/imfuxiao/Hamster/assets/154674265/8a3d8e07-181b-49ec-bc57-d1b11dcf8094)
![IMG_6734](https://github.com/imfuxiao/Hamster/assets/154674265/e96a4853-5949-4a7b-b7ec-7e587a7a6e92)

**Comment by imfuxiao** [comment]
`states` 不能注释

**Comment by LO-H-W** [comment]
谢谢您的回复，不过我可能越级挑战了，终究无法排除。

![IMG_6739](https://github.com/imfuxiao/Hamster/assets/154674265/6674e318-a478-4a69-a563-ea975c4f7470)

**Comment by LO-H-W** [comment]
原来好像是需要修改下这个资料夹的xxx.schema.yaml档，或者都需要？
![1895CB1F-9E07-4273-AD55-F888498FCE33](https://github.com/imfuxiao/Hamster/assets/154674265/ec71597f-4a66-46de-8eb2-9348abd0e03f)

总之，虽然仍有瑕疵但已成功解决使用痛点，
谢谢。

![F00C09B9-ED37-4CBB-AAD9-C625C7D3E280](https://github.com/imfuxiao/Hamster/assets/154674265/58cd8648-1f94-40dc-bb70-bad47a98bdeb)

**Comment by imfuxiao** [comment]
请查阅[「文档 」](https://ihsiao.com/apps/hamster/docs/FilesManager.html)

**Comment by LO-H-W** [comment]
谢谢！

**Comment by iTomxy** [comment]
@imfuxiao 你好，我似乎要要在檔案管理 -> 鍵盤檔案 -> build/default.yaml 中的 switcher/save_options 加上 simplification 才能保持繁简状态，但这一重新部署就会消失。

我是在檔案管理 -> 應用程式檔案 -> Rime 中编辑 yaml 文件的，按[文件管理](https://ihsiao.com/apps/hamster/docs/guides/file_manager/)，这些改动会在重新部署时自动复制到鍵盤檔案内。

我的方案文件中：
```yaml
# 檔案管理 -> 應用程式檔案 -> Rime -> rytphings.schema.yaml
switches:
  - name: simplification
    states: [ 傳統 , 简化 ]
    # reset: 1
```
`reset` 已经注释掉。在 default.custom.yaml 中：
```yaml
# 檔案管理 -> 應用程式檔案 -> Rime -> default.custom.yaml
patch:
  switcher/save_options:
    - simplification
```
已将 `simplification` 加入 `save_options` 中。键盘划动设置：在鍵盤佈局 -> 中文 26 鍵 -> 劃動設定，给 a 加了个下划动作 `shortcutCommand(#RimeSwitcher)`。然后 RIME 部署。

现在的行为是：
- 默认繁体；
- 用 a 下划改成简体，可以；
- 换到另一个窗口打字，又是繁体。

即还是没有保持繁简状态。在檔案管理 -> 應用程式檔案 -> Rime -> default.yaml 的 switcher/save_options 中加入 simplification 也不行。只有在檔案管理 -> 鍵盤檔案 -> build/default.yaml 中的 switcher/save_options 加上 simplification 才行。

- 「仓」输入法版本：2.16.4(1)
- RIME 版本：1.13.1
- iOS 版本：18.5

**Comment by imfuxiao** [comment]
不要在「键盘目录」下做修改，而应该在「应用目录」下在修改。

具体原因请查阅：https://ihsiao.com/apps/hamster/docs/guides/file_manager/

Thanks & Best Regards

付啸(morse)
Email: ***@***.***

**Comment by iTomxy** [comment]
「应用目录」应该就是指这个「應用程式檔案」吧？我就是在这里改 default.yaml 和 default.custom.yaml，然后重新部署，但无效。

 default.yaml：
```yaml
# 方案选单相关
switcher:
  caption: 「方案选单」
  hotkeys:
    - F4
    - Control+grave
    - Control+Shift+grave
    # - Alt+grave
  save_options:
    - ascii_punct
    - traditionalization
    - emoji
    - full_shape
    - search_single_char
    - simplification           # <- 加上了
  fold_options: true
  abbreviate_options: true
  option_list_separator: ' / '
```
default.custom.yaml：
```yaml
customization:
  distribution_code_name: hamster
  distribution_version: ""
  generator: "Rime::SwitcherSettings"
  modified_time: "Wed Feb  5 20:14:41 2025"
  rime_version: 1.12.0

patch:
  schema_list:
    - {schema: rytphings}
    - {schema: tupa}

  # switcher/save_options:     # <- 这样写也不行
  switcher/save_options/+:
    - simplification           # <- 也加了
```
![Image](https://github.com/user-attachments/assets/023f2361-01a3-43d2-adbc-73894beb0a2b)
