### ISSUE TITLE
如何在自定义键盘里设置用一键输入两个字母？

### ISSUE THREAD

**Issue by gkovacs** [imfuxiao/Hamster#507]
我的rime方案里设置了";"为反查键，我的目标是可以通过上滑反查对应的字母。

我试过用sendKeys但是上滑时什么都不会输出。我的键盘方案如下 ( https://github.com/gkovacs/rime-ios-config/blob/master/hamster.custom.yaml )

```
    - name: jyutping
      isPrimary: true
      rows:
        - keys:
            - action:
                character:
                  char: 'q'
              label: "手"
              swipe:
                - direction: up
                  action:
                    shortcutCommand:
                      sendKeys:
                        keys: ';q'
                  display: false
                  processByRIME: true
```

在同文输入法（安卓rime应用）可以这样实现我想要的功能：

```
  lookup_q: {functional: false, text: '{;}{q}'}
```

可不可以用仓输入法的自定义键盘来实现这个功能？（用一键输入两个字母）
