### ISSUE TITLE
不知能否自定义显示字体

### ISSUE THREAD

**Issue by YLXDXX** [imfuxiao/Hamster#511]
初次使用，在软件中没找到自定义字体的选项。
五笔用户，需要显示对应字的拆分规则，由于没法自定义字体，字的拆分符号没法正常显示。
下图为电脑上的效果
![image](https://github.com/imfuxiao/Hamster/assets/35033878/42474df4-9ace-4dd9-9ac3-d0031c4024c0)
手机上，comment中的拆分符号无法正常显示

**Comment by Jmdayou** [comment]
测试版已经支持了，慢慢等正式版上线吧。

**Comment by YLXDXX** [comment]
✌️，静候

**Comment by yzlnew** [comment]
这个应该如何设置呢，按照 yaml 里面的配置无法生效

**Comment by YLXDXX** [comment]
下面是我的设置，供参考：
1. 在方案目录下建立 Fonts 文件夹，将所需字体拷入
2. 在方案目录下新建 hamster.custom.yaml 文件，在其中设置对应的字体，如
```
patch:
  keyboard:
    style:
      fontFace:
        - name: "PingFangTC-Regular"
        - url: "xxx.otf"
```
