### ISSUE TITLE
自定义键盘中英文切换无显示

### ISSUE THREAD

**Issue by tywtyw2002** [imfuxiao/Hamster#524]
自定义键盘定义了空格左边的键为中英文切换，但是没有显示

3.0（182） ios 15.8

![IMG_1902](https://github.com/imfuxiao/Hamster/assets/576954/7fa010d5-b30b-4df7-88c7-e6034aa04d3f)

```
  - action:
      shortcutCommand: "#中英切换"
    width:
      portrait:
        percentage: 0.1
      landscape: available
```

PS. 有几个关于自定的键盘的使用疑问
1. 目前自定义键盘的`enter`键可以做到动态显示label吗？ 不同场景下是`发送`，`搜索`，`换行`等。
2. 目前自定义键盘可以做到像ios原生pinyin键盘一样，在网址或者email的场景下自动在空格右边多出一个按键来快捷输入`.` `@`？
3.
