### ISSUE TITLE
仓.九宫格的英文模式无法唤起custom_phrase

### ISSUE THREAD

**Issue by Nothend** [imfuxiao/Hamster#537]
作者大大好，使用仓九宫格，无论中文或者英文（26键），custom-phrase都无法唤起，但是，使用雾凇方案26键可以。是目前不支持还是需要设置什么？感谢

**Comment by iDvel** [comment]
九宫格方案里写了注释了：
```yaml
# 自定义短语：custom_phrase_t9.txt
# ⚠️ 编码要用数字
custom_phrase:
  dictionary: ""
  user_dict: custom_phrase_t9
  db_class: stabledb
  enable_completion: false
  enable_sentence: false
  initial_quality: 99
```

需要自己创建 `custom_phrase_t9.txt` 并写入：
```
# Rime table
# coding: utf-8
#@/db_name	custom_phrase_t9.txt
#@/db_type	tabledb

的	3
的	33
```
