### ISSUE TITLE
键盘支持非整行布局

### ISSUE THREAD

**Issue by tansongchen** [imfuxiao/Hamster#564]
最近想基于 17 键格道双拼和声笔输入法设计一个 22 键输入方案，类似于百度输入法的键盘内笔划筛选

![B55B6C09B7CBE62744456128DD0B747B](https://github.com/imfuxiao/Hamster/assets/31927845/e84df603-4a86-448c-aefd-eda83ddb5882)

但是，仓似乎只能按整行来设计键盘。未来是否有可能支持这种？

**Comment by imfuxiao** [comment]
有点难，之前想过做跨行的自定义布局，但没搞定，后面有时间了在研究下。

**Comment by lost-melody** [comment]
从配置文件结构上给出一点建议，具体实现层面我不了解，也就不细说。

- 将键盘布局元素分为三类：`Row`, `Column` 和 `Key`，前两者为「容器」，后者为「按键」。
- `Row` 作为行布局容器，内容元素横向排布。现有的 `Row` 模型就是这类容器。
  - `height`: 成员字段，描述行高。
  - `keys`: 成员字段，引入横向排布的按键列表。
  - ~`rows`: 成员字段，引入横向排布的嵌套行容器列表。~
  - `cols`: 成员字段，引入横向排布的嵌套列容器列表。
- `Column` 作为列布局容器，内容元素纵向排布。现有的 `Keyboard` 模型可看做这类容器，其 `rows` 字段定义的行是列排布的。
  - `width`: 成员字段，描述列宽。
  - `keys`: 纵向排布的按键列表。
  - `rows`: 纵向排布的行容器列表。
  - ~`cols`: 纵向排布的列容器列表。~
- 规定 `Keyboard` 自身是一个列布局容器。
- 容器的 `keys`, `rows`, `cols` 字段是两两互斥的。

> - 或许可以在 `Row` 和 `Column` 下增加 `overflow` 字段用于描述此布局是否可以滚动 (类似九宫数字键盘的符号)，但这明显和按键的划动手势冲突。
> - 禁止 `Row` 和 `Column` 直接包含同类容器，或许有助于理解和实现。

示例：

```yaml
# 一个简单 Row 模型
height: 56
keys:
  - action: { character: { char: a } }
  - action: { character: { char: b } }
  - action: { character: { char: c } }
#
#     ┌───┬───┬───┐
#     │ a │ b │ c │
#     └───┴───┴───┘
#
```

```yaml
# 由两个 Column 构成的嵌套 Row 模型
height: 168
cols:
  # col.1
  - width: 56
    keys:
      - action: { character: { char: "+" } }
      - action: { character: { char: "-" } }
      - action: { character: { char: ":" } }
  # col.2
  - width: 168
    rows:
      # row.2a
      - height: 56
        keys:
          - action: { character: { char: a } }
          - action: { character: { char: b } }
          - action: { character: { char: c } }
      # row.2b
      - height: 56
        keys:
          - action: { character: { char: "1" } }
          - action: { character: { char: "2" } }
          - action: { character: { char: "3" } }
      # row.2c
      - height: 56
        keys:
          - action: { character: { char: x } }
          - action: { character: { char: y } }
          - action: { character: { char: z } }
#
#     col.1     col.2
#    ┌───────────────────┐
#    │┌───┐ ┌───────────┐│
#    ││ + │ │ a | b | c ││ row.2a
#    ││---│ ├───────────┤│
#    ││ - │ │ 1 | 2 | 3 ││ row.2b
#    ││---│ ├───────────┤│
#    ││ : │ │ x | y | z ││ row.2c
#    │└───┘ └───────────┘│
#    └───────────────────┘
#
```
