### ISSUE TITLE
九宫格的上滑手势

### ISSUE THREAD

**Issue by Yzcloud** [imfuxiao/Hamster#568]
你好，能否为九宫格添加上滑手势支持或者工具栏快捷键，因为有些App不支持回车键（换行），特别需要这个功能。还有就是定制工具栏能否把Emoji加上去呢？

**Comment by wxmbaci** [comment]
九宫格支持上划，需要使用配置添加，具体可以看文档
https://ihsiao.com/apps/hamster/docs/CustomKeyboard.html#action-%E9%80%89%E9%A1%B9
增加配置文件 hamster.custom.yaml，重新部署生效。下面是部分片段
````
patch:
   swipe:
     keyboardSwipe:      
     - keyboardType: chineseNineGrid
       keys:
         - action: { chineseNineGrid: { symbol: { char: "@/." } } }
           swipe:
             - direction: up
               action: { symbol: { char: "1" } }
````
