### ISSUE TITLE
BUG 反馈：主键盘是九宫格，划动距离阈值 、角度阈值 配置未生效

### ISSUE THREAD

**Issue by wxmbaci** [imfuxiao/Hamster#586]
主键盘是九宫格，划动距离阈值 、角度阈值 配置未生效
配置方式: 使用配置文件设置参数，重置 ui 后重新部署。其他配置生效，划动距离阈值 、角度阈值 配置未生效
版本: 2.4.1
输入方案:雾凇

**Comment by imfuxiao** [comment]
您好，我测试是可以生效的。

配置调整如下：
```yaml
patch:
  swipe:
    # 划动距离阈值，当划动的距离大于或等于此值时，才会识别为一次划动
    distanceThreshold: 40
    # 此值是正切角度的阈值，用来限制上下左右划动时的角度，如果太大容易误触
    # 默认为 15 度的正切值，即上下左右划的的角度不能超过 15 度
    # tan(10º) ≈ 0.176, tan(15º) ≈ 0.268, tan(30º) ≈ 0.577, tan(45º) = 1, tan(60º) ≈ 1.732
    tangentThreshold: 0.577
```
