### ISSUE TITLE
`rime_api:get_user_data_dir()` 等是否可以换成应用文件而不是键盘文件？

### ISSUE THREAD

**Issue by sci-42ver** [imfuxiao/Hamster#593]
**您的功能请求是否与某些问题有关？请描述**
参考[rime-fast-xhup](https://github.com/boomker/rime-fast-xhup/blob/master/lua/en_custom.lua)，尝试英文自造词修改 `en_dicts/en_custom.dict.yaml`，但是其修改的是键盘文件，而不是应用文件。而目前配置文件都是在应用文件。

同步之后，并不会同步 `en_dicts` 文件夹。

**描述您想要的解决方案**
提供一个接口可以修改 应用文件。由于用的沙箱，应用文件真实路径不是太清楚。键盘文件路径可以通过回显得到 `/private/var/mobile/Containers/Shared/AppGroup/foo/InputSchema/Rime`，不过由于沙箱，不太好推出应用文件位置。

可能这个要求和设计及安全相悖。不知道您有没有好的办法？

**描述您考虑过的替代方案**
`rime_api:get_user_data_dir()` 等 换成应用文件而不是键盘文件。

**其他**
在此处添加有关功能请求的任何其他上下文或截图或视频等等。

**Comment by imfuxiao** [comment]
您好，仓的文件存储设计如下：

![image](https://github.com/imfuxiao/Hamster/assets/6482586/73bdf289-3faa-45d5-8db6-c508fce368e9)

具体描述请查阅[「文件管理」](https://ihsiao.com/apps/hamster/docs/FilesManager.html)。

看你的需求：[rime-fast-xhup](https://github.com/boomker/rime-fast-xhup/blob/master/lua/en_custom.lua) 是在键盘使用中将英文自造词直接写到 `en_dicts/en_custom.dict.yaml` 中了。

而你的问题是，仓的同步不会把修改过的 `en_dicts/en_custom.dict.yam`文件从键盘目录复制到应用目录下，导致同步无效。

---

这个问题其实不需要更换目录的，你看截图中的红色部分，仓在执行同步的过程中，有个选项会对自造次文件进行复制，从「键盘目录」复制到「应用目录下」。具体复制的内容有个参数可以控制，下面是默认的配置。

```yaml
rime:
  # 覆盖词库文件的正则表达式
  # 使用场景：
  # 在开启 overrideDictFiles 后，每次重新部署会按照正则表达式符合的条件翻盖文件
  regexOnOverrideDictFiles:
    - "^.*[.]userdb.*$"
    - "^.*[.]txt$"
```

您可以在加个参数，如`^.*en_custom.dict.yaml`，我理解这样就可以满足你的需求了。

**Comment by sci-42ver** [comment]
感谢您的及时回复。刚才我按照[一般 translator 设计](https://github.com/hchunhui/librime-lua/issues/318#issue-2149770533)改成同步到 userdb，可以作为一个变通的解决方法。

可能我表述有点问题，我想要把键盘文件复制到应用文件，所以应该修改 `regexOnCopyAppGroupDictFile`。

之前编辑 `hamster.custom.yaml` 有部分参数没在意，漏掉了上述的 `regexOnCopyAppGroupDictFile`。

**Comment by sci-42ver** [comment]
请问一下，目前我的 sync 文件夹如下所示
```bash
$ ls # in sync dir
fcitx5/
iphone/
README.md
windows/
```
然后 当我的 fcitx5/ 之类文件夹更新后 (在应用文件里)，我想要把他拷贝到键盘文件。于是我使用 `overrideDictFiles: true`。但是这样，貌似始终会无法产生自造词。 https://github.com/imfuxiao/Hamster/blob/9a7f01ff67b84d2522bb9f50068d42434c1368c4/Packages/HamsterKeyboardKit/Sources/RimeContext/RimeContext.swift#L237
由于 `regexOnCopyAppGroupDictFile` 并不充当 sync 的功能 https://github.com/imfuxiao/Hamster/blob/9a7f01ff67b84d2522bb9f50068d42434c1368c4/Packages/HamsteriOS/Sources/ViewModel/Finder/FinderViewModel.swift#L125
故可能只能自己修改代码编译 (手上没有 Mac，不太好弄)。

可以 `overrideDictFiles: true` 的同时，使用 `regex` 来排除 override 的对象么？即拷贝 fcitx5，windows 到键盘文件，但是保留 iphone。

**Comment by imfuxiao** [comment]
如配置文件所示，使用自造词请将参数 `overrideDictFiles` 改为 false
<img width="776" alt="image" src="https://github.com/imfuxiao/Hamster/assets/6482586/84c2a0e5-9b7f-4acf-ae61-7a7fc7588042">

**Comment by imfuxiao** [comment]
另外，如下图：
<img width="865" alt="image" src="https://github.com/imfuxiao/Hamster/assets/6482586/890dbfcf-c2c6-4222-af03-3b7fc811596d">

也就是说，你只需要把你在键盘上生成的的 `xxx.userdb` 目录下的全部复制到「应用目录」，然后同步就可以了。

**Comment by imfuxiao** [comment]
同步示例可以参考 wiki ：https://github.com/imfuxiao/Hamster/wiki/%E5%90%8C%E6%AD%A5%E6%95%99%E7%A8%8B

**Comment by sci-42ver** [comment]
> 也就是说，你只需要把你在键盘上生成的的 `xxx.userdb` 目录下的全部复制到「应用目录」，然后同步就可以了。

感谢您的耐心回复。之前脑子有点糊涂，代码没看完整
https://github.com/imfuxiao/Hamster/blob/9a7f01ff67b84d2522bb9f50068d42434c1368c4/Packages/HamsterKeyboardKit/Sources/RimeContext/RimeContext.swift#L339-L340

```yaml
overrideDictFiles: false
regexOnOverrideDictFiles:
      - "^.*[.]userdb/.*$" # this is binary userdb dir
      - "^.*iphone.*[.]txt$" # to avoid iphone be overwritten but not for others.
```
上述 yaml 可以确保 `regexOnOverrideDictFiles` 会先备份到应用文件，然后剩余文件默认全部覆盖。`userdb/` 来避免把键盘文件 `fcitx5/...userdb.txt` 备份同时确保 db 文件可以备份从而生成自造词。
