### ISSUE TITLE
「Bug」使用`hamster.custom.yaml`设置字体后，键盘配色无效问题

### ISSUE THREAD

**Issue by kingdream123** [imfuxiao/Hamster#623]
**Bug的详细描述**
在 Rime 目录下新增`hamster.custom.yaml`自定义配置文件指定字体，内容如下
```yaml
patch:
  keyboard:
    style:
      fontFace:
        - name: "SymbolsNFM"
        - url: "SymbolsNerdFontMono-Regular.ttf"
```

**Bug 的复现过程**
1. 增加上述文件后，重新部署
2. 进入到软件【键盘配色】设置中，配色方案无法显示
3. 移除`hamster.custom.yaml`后，重新部署，配色方案显示恢复正常

**您的预期行为**
是否可以使用`hamster.custom.yaml`文件来打patch

**屏幕截图/视频**
![08f9c3baa44edfbbd065fbe0be9b0767](https://github.com/imfuxiao/Hamster/assets/14135124/4beef7f8-034b-4ca0-9faf-a0677995f495)

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 17.4.1
 -  仓输入法版本：商店版 1.10.0

**其他**

是否可以使用`hamster.custom.yaml`文件来打patch
