### ISSUE TITLE
「Feature」有关“部署时覆盖词库文件”冲突问题

### ISSUE THREAD

**Issue by chca2** [imfuxiao/Hamster#640]
**您的功能请求是否与某些问题有关？请描述**
付佬，昨天看到有个淞鹤拼音，我在群里也推荐了，主要是解决了雾淞和小鹤音形合并的问题。
由于雾淞和小鹤音形采用不同的自造词逻辑：雾淞有自造词、小鹤音形没有自造词。二者逻辑彼此冲突，在同时使用两种方案在仓上就会有问题。“部署时覆盖词库文件”选项的说明是“如果您未使用自造词功能，请保持开启状态”。
考虑到淞鹤是结合了音形和双拼（拼音），使用前者时候应开启、后者不应开启。
实践中，关闭时也会发生xhup_dicts中的词语定义后无法生效的情况。但是如果开启该功能，是不是又会影响使用双拼（拼音）时候的自造词功能（userdb）?

**描述您想要的解决方案**

我给淞鹤拼音的作者提了这个问题，他答复：好问题，理论上确实应该是应该是有冲突的。

这个问题估计需要 @imfuxiao 来解决一下。比较好的做法是，关闭“部署时覆盖词库文件”选项的时候只影响用户词库 userdb 而不影响码表文件 xhup_dicts/* 才对，这里的逻辑也要请作者核实一下。

**描述您考虑过的替代方案**
简明扼要地描述您考虑过的任何替代解决方案或功能。

**其他**
在此处添加有关功能请求的任何其他上下文或截图或视频等等。

**Comment by imfuxiao** [comment]
「雾淞有自造词、小鹤音形没有自造词」我理解并不冲突，因为「小鹤音形」并没有用户词库，所以你完全可以已有「自造词」的方案关闭「部署时覆盖词库文件」选项。


使用「自造词」功能，必须关闭「部署时覆盖词库文件」选项。

在关闭此选项后，方案每次「部署」时，会 Copy 键盘中的「自造词」词库文件到应用目录下，就不会出现「自造词」被覆盖的问题。

**Comment by kchen0x** [comment]
@chca2 所以你在测试过程中确实出现过“关闭时会发生xhup_dicts中的词语定义后无法生效的情况”？

可不可以说一下复现的步骤，根据 @imfuxiao 的描述，现有的逻辑应该是对的。

> BTW，请确认你的“鹤”自造词是在 xhup_dicts/xhup.user.dict.yaml 或 xhup_dicts/xhup.user.top.dict.yaml 两个码表文件中添加的。

**Comment by chca2** [comment]
我是使用的iCloud配置文件，每次在仓中使用自带文件管理功能手动加词也是在iCloud的文件。
在关闭时，重新部署正常仓会copy iCloud中的配置文件，自然也包括xhup_dicts中的词语定义，但重新部署后新加词并不生效。如果开启功能，就不会这样。

**Comment by imfuxiao** [comment]
没有看动你的描述，如我[帮助手册](https://ihsiao.com/apps/hamster/docs/Sync.html)中的描述：

----
「RIME 同步」和「iCloud 同步」。这两种同步功能，功能不同，使用场景也不同。

RIME 引擎的自带的同步功能，主要是同步不同设备的自造词文件（当然也包含一些配置文件）。

iCloud 同步使用的是苹果的文件同步功能，主要是将文件同步到云端。

根据同步功能特点：

场景一：使用自造词，且希望不同的设备可以同步自造词。建议使用：「RIME 同步」功能。
场景二：不使用自造词，只希望同步输入方案及应用配置。建议使用：「iCloud 同步」功能。
----

「部署时覆盖词库文件」选项是使用 「RIME 自造词」必须要关闭的，它会根据 `regexOnOverrideDictFiles` 中的正则表达式去处理需要覆盖的文件，默认配置如下：

```yaml
# RIME 引擎相关配置
rime:
  # 覆盖词库文件的正则表达式
  # 使用场景：
  # 在关闭 overrideDictFiles 后，每次重新部署时，用键盘目录下匹配正则的文件去覆盖应用目录下的文件
  regexOnOverrideDictFiles:
    - "^.*[.]userdb.*$"
    - "^.*[.]txt$"
```

而是你说的加词，我猜测是修改了固定词的 txt 文件，如果是我猜测的情况，根据上面默认正则表达式，txt 文件，当在关闭「部署时覆盖词库文件」选项后，每次运行「重新部署」时，都会用键盘下的相同 txt 文件去覆盖应用下的 txt 文件，所以就会导致加的词丢失。

你需要添加 `hamster.custom.yaml` 文件，文件内容可以添加已下配置：

```yaml
patch:
  rime/regexOnOverrideDictFiles:
    - "^.*[.]userdb.*$"
```

如果不是我猜想的情况，需要你重新描述，最好可以详细描述你的配置，具体操作，越具体越好。
