### ISSUE TITLE
「Feature」希望可以区分左右划动与长按动作的延迟时间

### ISSUE THREAD

**Issue by xiaotianxt** [imfuxiao/Hamster#665]
**您的功能请求是否与某些问题有关？请描述**
在目前配置结构下，「空格键左右划动的延迟时间」，和「其他按钮的长按延迟时间」全部由 `swipe/longPressDelay` 来控制。
默认情况下 `longPressDelay` 被设置为 0.3s，此时使用空格进行左右划动不跟手，难以控制。
然而，如果降低 "longPressDelay"，在打字的时候，比较容易误触发长按钮模式。

**描述您想要的解决方案**
希望可以通过增加 spaceLongPressDelay 来特别区分空格按键的长按钮延迟，进而解决两种不同操作的耦合问题。

```yaml
  swipe:
    # 指空格移动多个 point，光标移动一位。所以数字越小越灵敏
    spaceDragSensitivity: 15

    # 划动距离阈值，当划动的距离大于或等于此值时，才会识别为一次划动
    distanceThreshold: 20

    # 此值是正切角度的阈值，用来限制上下左右划动时的角度，如果太大容易误触
    # 默认为 15 度的正切值，即上下左右划的的角度不能超过 15 度
    # tan(10º) ≈ 0.176, tan(15º) ≈ 0.268, tan(30º) ≈ 0.577, tan(45º) = 1, tan(60º) ≈ 1.732
    tangentThreshold: 0.577
    # 长按延迟时间，只要大于或等于此阈值，才会触发长按 Action，如空格划动
    longPressDelay: 0.1
    # 自带键盘引入，hamster_swipe 为键盘文件名称
    keyboardSwipe:
      __include: hamster_swipe:/keyboardSwipe
```
