### ISSUE TITLE
「Feature」自定义布局中按下 Shift 后按键显示不同文本

### ISSUE THREAD

**Issue by huxiangyou** [imfuxiao/Hamster#695]
希望可以支持在自定义布局中，按下`Shift`键后，按键的`label`显示文本可以由配置指定不同的文本。

例如：韩语键盘中，不按`Shift`时，按键`q`显示`ㅂ`，而按下`Shift`后，这个按键显示`ㅃ`。

配置文件中可以像这样：
```yaml
- action: { character: { char: q } }
  label:
    lower: "ㅂ"
    upper: "ㅃ"
```

因为现在`character`和`Shift`状态是捆绑的（#485），所以上例中可以在`schema`中配置大小写`q`和`Q`分别对应这两个字母，所以只需要让显示出来的文本可以随`Shift`自动变化就好。之前想过做成两套键盘布局，在按下假的`Shift`键（仿造`Shift`的外观但实际功能是`keyboardType`）时自动切换到第二套，再在按下按键后自动切换回来（类似#449），但在此例中可以不用这样做。
