### ISSUE TITLE
关于自定义 OpenCC 字形转换的问题

### ISSUE THREAD

**Issue by yikyuencheung** [imfuxiao/Hamster#72]
开发者好，

我在使用仓输入法时遇到一个问题：似乎目前产品还不支援基于 OpenCC 的字形转换。

我在使用中会使用一个冷门的中文正字转换规则，目前在电脑端可以使用，但在仓输入法内无法实现字形转换的效果。方案见附件。

[dzing.zip](https://github.com/imfuxiao/Hamster/files/11260530/dzing.zip)

烦请排查，感谢。

**Comment by imfuxiao** [comment]
您好, 您提供的输入方案不全, 可以将您PC端的输入方案整个打包后提供下, 方便测试.

**Comment by yikyuencheung** [comment]
感谢。这个转换规则主要用在 Luna Pinyin 方案里，但为防遗漏我打包了目前所有配置文件。

https://www.transferfile.io/#/bafybeihhh7l5fcszvyvhxytmnfsnb5cccgh32nbuewln7ceze2omh35wje

**Comment by imfuxiao** [comment]
![IMG_2AF9D52B75A5-1](https://user-images.githubusercontent.com/6482586/232965796-d205a540-ed19-4701-9097-d7701c2cc731.jpeg)

您好, 用您提供配置有两种输入方案: 明月和粤语, 截图是粤语的, 我测试是正常的.

**Comment by yikyuencheung** [comment]
感谢，问题的重点在于字形转换的部分似乎无法调起或没有正常工作。

我的这个配置文件中，在 Luna Pinyin 里有单独设定不同的字形转换方案，譬如「港汉」「台汉」等。其中的「我流」即使用我开始时提到的那个 dzing_variants 的字形转换方案。

我通常会用「世界」「时间」等词汇测试，如果打出来的字形是「世畍」「旹間」，就说明这个方案生效了。

麻烦了。

**Comment by imfuxiao** [comment]
> 感谢，问题的重点在于字形转换的部分似乎无法调起或没有正常工作。
> 
> 我的这个配置文件中，在 Luna Pinyin 里有单独设定不同的字形转换方案，譬如「港汉」「台汉」等。其中的「我流」即使用我开始时提到的那个 dzing_variants 的字形转换方案。
> 
> 我通常会用「世界」「时间」等词汇测试，如果打出来的字形是「世畍」「旹間」，就说明这个方案生效了。
> 
> 麻烦了。

您好, 麻烦提供下世界和时间对应提供的输入键值, 尤其是粤语...

**Comment by yikyuencheung** [comment]
啊其实不用特别测试粤拼，我平时主要也在明月拼音里使用这个转换方案。就直接打拼音就好了。

感谢。

粤拼的话是 sai gaai 和 si gaan。

**Comment by imfuxiao** [comment]
![IMG_0001](https://user-images.githubusercontent.com/6482586/233015579-3517ff49-90c7-4fa3-a9db-2108773e93b5.PNG)

您好, 您看这样是生效了吧

**Comment by yikyuencheung** [comment]
是的！

**Comment by imfuxiao** [comment]
我修改了您的配置.

```yaml
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 西文 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - options: [ variants_hk, trad_tw, simplification, woliu ]
    states: [ 港漢, 臺漢, 简汉, 我流 ]
    # 修改下行，改變預設用字 [0, 1, 2, 3 --> 對應上表]
    # Edit the following line to change the default character style
    #    [0 = OpenCC Traditional Chinese; 1 = Hong Kong TC; 2 = Taiwan TC; 3 = Mainland Simplified Chinese]
    # Or reove to remember user setting
    reset: 3
  - name: woliu
    states: [ "0", "1" ]
    reset: 1
  - name: ascii_punct
    states: [ 。，, ．， ]
  - name: emoji_suggestion
    # 取消下行註釋，預設啓動 emoji
    reset: 1
    states: [ 冇 Emoji, 有 Emoji ]
```
