### ISSUE TITLE
无法设置按键圆角为方角

### ISSUE THREAD

**Issue by dustsoar** [imfuxiao/Hamster#724]
**Bug的详细描述**
个人习惯将按键圆角设置为0，也就是变成方角，但导入文件后按键始终带有圆角

**Bug 的复现过程**
自定义corner_radius: 0，但实际按键始终有圆角

**您的预期行为**
希望可以修改圆角

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 18.3.1
 -  仓输入法版本：商店版 2.6.1

**Comment by imfuxiao** [comment]
根据您说的情况我在「自定义键盘」功能与「键盘皮肤」功能中测试，没有复现您说的问题。

* 自定义键盘测试样本：

![Image](https://github.com/user-attachments/assets/79cec5b3-ac2c-4861-b909-abe473546fe4)

```yaml
...
    keyStyle:
      {
        "测试":
          {
            borderSize: 0.0,
            buttonBackgroundColor: 0xFF1F3ACF,
            cornerRadius: 0.0,
            fontSize: 12.0,
            swipeFontSize: 10.0,
          },
      }
    name: "测试键盘"
    rows:
      [
        {
          keys:
            [
              {
                action: { character: { char: q } },
                callout: [],
                darkModeStyleName: "测试",
                label: { loadingText: "", systemImageName: "", text: "手" },
                lightModeStyleName: "测试",
                processByRIME: true,
                swipe:
                  [
                    {
                      action: { character: { char: 1 } },
                      direction: up,
                      display: true,
                      label: { loadingText: "", systemImageName: "", text: "" },
                      processByRIME: false,
                    },
                  ],
                width: { landscape: input, portrait: input },
              },
...
```

*  键盘皮肤测试样例

![Image](https://github.com/user-attachments/assets/c5e81cfc-b76f-461d-ad45-09c4a7acc90a)

```yaml
# 字母按键背景样式
alphabeticButtonBackgroundStyle: &alphabeticButtonBackgroundStyle
  type: original
  insets: { top: 6, left: 3, bottom: 6, right: 3 }
  normalColor: FFFFFF
  highlightColor: ABB0BA
  cornerRadius: 0
  normalLowerEdgeColor: 88898D
  highlightLowerEdgeColor: 89898B
  animation: alphabeticBackgroundAnimation
```
